---
title: "Oct-9-2024"
format: html
---

#set up
```{r}
rm(list = ls())
library(tidyverse)
library(here)
```

#read in tomato data
```{r}
tomatoes <- read.csv(here("data", "tomato_data.csv"))
glimpse(tomatoes)
```

#fix treatment levels
```{r}
tomatoes$Treatment <- as.factor(tomatoes$Treatment)
levels(tomatoes$Treatment)

fix <- which(tomatoes$Treatment == "control")
tomatoes$Treatment[fix] <- "Control"

fix2 <- which(tomatoes$Treatment == "fertilizer")
tomatoes$Treatment[fix2] <- "Fertilizer"

tomatoes$Treatment <- factor(tomatoes$Treatment)
levels(tomatoes$Treatment)

tomatoes$Plant_number <- as.factor(tomatoes$Plant_number)
```

#Warm-up exercises
```{r}
#return the 3rd, 7th, and 9th rows of data
tomatoes |> slice(c(3, 7, 9)) |> View()

#return all tomatoes from the fertilizer treatment that 
#weigh greater than or equal to 145g
tomatoes |> 
  filter(Treatment == "Fertilizer", 
         Avg_tomato_weight_g >= 145)
  
```



#save changes 
make the output folder
```{r}
#dir.create(here("Outputs"))
```

save the file
```{r}
write.csv(tomatoes, here("Outputs", "tomatoes_fixed.csv"), row.names = F)
```

```{r}
toms2 <- read.csv(here("Outputs", "tomatoes_fixed.csv"))
```

#Working with lead data
```{r}
lead <- read.csv(here("data", "NoCoLead.csv"))
head(lead)
summary(lead)
```

Avg number of tests given in the data set
```{r}
lead |>
  summarise(mean_num_tests = mean(num_tests)) |>
  View()
```

Mean number of tests per year
```{r}
lead |>
  group_by(Year) |>
  summarise(mean_num_tests =
              mean(num_tests)) |>
  View()
```

